from distutils.core import setup, Command

from cycodegenlib import version

CLASSIFIERS = ['Development Status :: 1 - Planning',
               'Intended Audience :: Developers',
               'License :: OSI Approved :: MIT License',
               'Programming Language :: Python',
               'Topic :: Software Development :: Libraries :: Python Modules']

setup(name="cython-codegen",
        packages = ['cycodegenlib'],
        scripts = ['scripts/xml2cython.py'],
        description="cycodegenlib - an hack to generate cython code from xml output generated by gccxml",
        #long_description = __doc__,
        author="David Cournapeau",
        #author_email="",
        license="MIT License",
        version = version,
        classifiers = CLASSIFIERS,)
        #zip_safe = True)
