from distutils.core import setup, Command

setup(name="cython-codegen",
        packages = ['cycodegenlib'],
        scripts = ['scripts/xml2cython.py'],
        description="cycodegenlib - an hack to generate cython code from xml output generated by gccxml",
        #long_description = __doc__,
        author="David Cournapeau",
        #author_email="",
        license="MIT License",
        version = "0.2")
        #classifiers = classifiers,
        #zip_safe = True)
