"""\
xml2cython: process xml files generated by gccxml and generate cython code from
it. """
import getopt
import sys

class Usage(Exception):
    def __init__(self, msg):
        self.msg = msg

def main(argv=None):
    if argv is None:
        argv = sys.argv

    # parse command line options
    try:
        try:
            opts, args = getopt.getopt(argv[1:], "h", ["help"])
        except getopt.error, msg:
            raise Usage(msg)
    except Usage, e:
        print >>sys.stderr, e.msg
        print >>sys.stderr, "for help use --help"
        return 2

    # process options
    for o, a in opts:
        if o in ("-h", "--help"):
            print __doc__
            return 0

if __name__ == '__main__':
    sys.exit(main())
