"""\
xml2cython: process xml files generated by gccxml and generate cython code

Usage:
    xml2cython xmlfile"""
import getopt
import sys

class Usage(Exception):
    def __init__(self, msg):
        self.msg = """\
usage: xml2cython [options] xmlfile

%s""" % msg

def main(argv=None):
    if argv is None:
        argv = sys.argv

    # parse command line options
    try:
        try:
            opts, args = getopt.getopt(argv[1:], "ho:", ["help", "output"])
            if len(args) > 1:
                raise Usage("Error, exactly one input file must be specified")
            input = args[0]
        except getopt.error, msg:
            raise Usage(msg)
    except Usage, e:
        print >>sys.stderr, e.msg
        print >>sys.stderr, "for help use --help"
        return 2

    # process options
    output = None
    for o, a in opts:
        if o in ("-h", "--help"):
            print __doc__
            return 0
        elif o in ("-o", "--output"):
            output = a

    if output is None:
        out = sys.stdout
    else:
        out = open(output, 'w')

    print "Parsing file", input
    print "Outputing to", out

if __name__ == '__main__':
    sys.exit(main())
